### PR TITLE
rolling to "self" gives option to send to players

### LINKED ISSUE #272: Re-introduce show to players button for private rolls
The `monitor_messages` function at the bottom of `MessageBroker.js` does this, but the class names need to be updated to match the class names on the encounters page.

### PR DESCRIPTION
**Pull request by bain2236**
resolves #272 
re did the monitor message function as an observer
watches combat log and adds in button on expanded rolls
hides button before it collapses
shows button again if opened

### CODE REVIEW

**Comment by Azmoria** [comment]
Works as expected - just some styling needed on the player side. This is my view from a 2nd account in firefox as a player. Good job though. 👍
image

**Comment by vlaminck** [comment]
I randomly get this error when I join as dm

```
helpers.ts:102 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at observe_messages (MessageBroker.js:1312:20)
    at init_ui (Main.js:2411:2)
    at Main.js:1621:4
    at EncounterHandler.js:49:5
    at Object.success (EncounterHandler.js:234:7)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.min.js:2:82355)
    at XMLHttpRequest.r (helpers.ts:77:19)
```

**Comment by vlaminck** [comment]
I also see the button showing up inside the expanded box like this:

Screen Shot 2022-04-23 at 1 06 59 PM


The original intent was to have it show up under the box like this:

original intent

**Review by vlaminck — CHANGES_REQUESTED** [review]
I also see the button showing up inside the expanded box like this:

Screen Shot 2022-04-23 at 1 06 59 PM


The original intent was to have it show up under the box like this:

original intent

**Comment by bain2236** [comment]
Ahh I guess it's hitting the observer before the game log has loaded in. 
Will move the button to the outside and have a think about the loading issue

**Comment by bain2236** [comment]
Just got some styling left to do, will sort out tomorrow

**Comment by vlaminck** [comment]
As we discussed in Discord, this is what I came up with. I'm sure there's more to it than this, but I didn't want it to get lost. 


    if (msg.eventType == "dice/roll/fulfilled") {
    
        ...

        if (msg.messageScope === "userId") {
            // this message was sent to self. Let's inject a "send to everyone" button
            let gamelogItem = $("ol.tss-jmihpx-GameLogEntries li").first();
            if (gamelogItem.find(".gamelog-to-everyone-button").length === 0) {
                const sendToEveryone = $(`<button class="gamelog-to-everyone-button">Send To Everyone</button>`);
                sendToEveryone.click(function (clickEvent) {
                    let resendMessage = msg;
                    resendMessage.id = uuid();
                    resendMessage.data.rollId = uuid();
                    resendMessage.messageScope = "gameId";
                    resendMessage.messageTarget = find_game_id();
                    resendMessage.dateTime = Date.now();
                    window.diceRoller.ddbDispatch(resendMessage);
                });
                gamelogItem.find("time").before(sendToEveryone);
             }
        }
        if (!window.DM)
            return;
        
        ...
    
    }

**Comment by bain2236** [comment]
re-worked this to work as mikedave mentioned. However to get it really nice it requires #408, this works for now. There's still a minor styling issue in FF which I can't seem to fix despite some effort. 
you also can't expand/collapse rolls, but I have removed the cursor events so at least it doesn't look like you can click on re-sent rolls

**Review by vlaminck — APPROVED** [review]

**Comment by vlaminck** [comment]
This has been merged into a feature branch and a new PR has been opened to replace this one https://github.com/cyruzzo/AboveVTT/pull/462

**Pull request closed without merging**
