### PR TITLE
Combat tracker face lift

### PR DESCRIPTION
**Pull request by Azmoria**
#303 - Doesn't close it if more functionality is wanted. Takes care of a visual update.

### CODE REVIEW

**Comment by vlaminck** [comment]
When this is ready for review, can you add a screenshot of what it looks like?

**Comment by Azmoria** [comment]
I think it's ready for review now. See example at: https://www.youtube.com/watch?v=NYJ548gz54c

**Comment by Azmoria** [comment]
https://discord.com/channels/815028457851191326/832199739398946817/955200895245758545

https://discord.com/channels/815028457851191326/832199739398946817/955203167962943528

Examples of the open monster sheet. It should only open a new monster/sheet when the monster iframe is already open.

**Comment by Azmoria** [comment]
accidently merged wrong will submit new pr

**Pull request closed without merging**
