### PR TITLE
Add blink to message log

### PR DESCRIPTION
**Pull request by dottertrotter**

### CODE REVIEW

**Comment by dottertrotter** [comment]
This adds a blinking inset shadow the message log if you are scrolled up when a new message is added.  Scrolling to the bottom removes the blinking.

Screen Shot 2021-12-03 at 8 25 08 AM

**Comment by cyruzzo** [comment]
This works nicely for the chat. But it doesn't work for the rolls.

Put some of your code into the notify_gamelog() function. That function gets called when the gamelog has something new to display. (it's currently used to make the gamelog button red if you're not in the gamelog). That should work.

**Comment by cyelis1224** [comment]
i dont know how to do a commit to someone elses fork but you are right cyruzzo, if he just changes it to:


function notify_gamelog() {
	if ($(".glc-game-log").is(":hidden")) {
		$("#switch_gamelog").css("background", "red");
	}
	if ($(".GameLog_GameLog__2z_HZ").scrollTop() < 0) {
		$(".GameLog_GameLog__2z_HZ").addClass("highlight-gamelog");
	}
}

it works from what I've tested.

**Review by cyelis1224 — COMMENTED** [review]
change the function notify_gamelog() to:


function notify_gamelog() {
	if ($(".glc-game-log").is(":hidden")) {
		$("#switch_gamelog").css("background", "red");
	}
	if ($(".GameLog_GameLog__2z_HZ").scrollTop() < 0) {
		$(".GameLog_GameLog__2z_HZ").addClass("highlight-gamelog");
	}
}

**Comment by dottertrotter** [comment]
@cyruzzo @cyelis1224 Updated code seems to work for both chat and dice rolls, etc.  Thanks.

**Pull request merged**
