### PR TITLE
Add ability to roll DDB dice with modifiers

### PR DESCRIPTION
**Pull request by vlaminck**
# What
This adds the ability to roll DDB dice with modifiers.  
`DiceRoller.js` was added, but it isn't implement in this PR. It will be implemented by some of the other open PRs.

# How It Works
`DiceRoller` works by 
1. Parsing an expression (such as 1d20+4)
2. Clicks the DDB dice buttons and then the DDB roll button
3. Captures the corresponding "dice/roll/pending" message
a. If the message metadata needs to be altered it will do so
b. The captured message is then sent as expected
5. Captures the corresponding "dice/roll/fulfilled" message
a. Parses the dice roll results
b. Calculates the original expression using the dice roll results
c. The captured message is then sent as expected

# How To Use It
Create a `DiceRoll` object, and pass it to `window.diceRoller.roll`.

## Example 1
The most basic use is to simply call it with an expression. This will roll dice on behalf of the Player or DM, and will use all the default metadata that DDB uses. This code will result in the screenshot below

    var diceRoll = new DiceRoll("2d20kh1+2");
    window.diceRoller.roll(diceRoll);

Screen Shot 2022-04-18 at 11 03 41 AM

## Example 2
To roll on behalf of a monster, you would call it like this

    var diceRoll = new DiceRoll("1d20-3");
    diceRoll.action = "Big Fist";
    diceRoll.rollType = "damage";
    diceRoll.entityId = monsterData.id;
    diceRoll.name = monsterData.name;
    diceRoll.avatarUrl = monsterData.avatarUrl;
    window.diceRoller.roll(diceRoll);

Screen Shot 2022-04-18 at 11 04 00 AM

# Demo
Here's a video demonstrating the expression "2d20kh1+2" which is rolling with advantage and a +2 modifier. The DDB dice rolled a 10 and a 4, resulting in the final expression of 10+2=12
avtt-diceRoller

### CODE REVIEW

**Review by Azmoria — APPROVED** [review]
This causes no issues for me. We spoke about how some complex formula's aren't accounted for and there's some issues with access to the game log's formulas of custom rolls (subtraction and kh / kl aren't always displayed properly for complex rolls). Even still I think this brings a lot of value and will work for the majority of cases. Awesome work 👍

**Review by Azmoria — APPROVED** [review]
Pretty sure you caught everything we spoke about.

**Comment by bain2236** [comment]
Looks good code wise and gave it a quick whirl and does the job nicely

**Comment by vlaminck** [comment]
This has been merged into a feature branch and a new PR has been opened to replace this one https://github.com/cyruzzo/AboveVTT/pull/462

**Pull request closed without merging**
