### PR TITLE
Add option to Group Tokens in Right-click menu

### PR DESCRIPTION
**Pull request by Rishabh2**
When selecting multiple tokens, tokens can be grouped so that clicking any one of them selects all of them.

Grouped tokens act as a single unit when clicked, right-clicked, or dragged.

image

### CODE REVIEW

**Comment by bain2236** [comment]
Nice. For icons we usually use https://fonts.google.com/icons?selected=Material+Icons I believe.
I'd also move the grouping down in the menu, stat blocks should always be at the top.

**Comment by Rishabh2** [comment]
> Nice. For icons we usually use https://fonts.google.com/icons?selected=Material+Icons I believe. I'd also move the grouping down in the menu, stat blocks should always be at the top.

Icons have been updated and button has been moved

**Comment by vlaminck** [comment]
If we choose to support this feature, I think it's more of a way to combine multiple tokens into a single token rather than a shortcut for selecting tokens. For the benefit of anyone that wasn't in the Discord conversation, the idea here is to allow grouping tokens together in a way that allows them to act as one. For example, a horse pulling a wagon could be grouped together and would then act as a single token rather than 2 separate tokens.

**Comment by vlaminck** [comment]
relates to https://github.com/cyruzzo/AboveVTT/issues/579

**Comment by Rishabh2** [comment]
The only remaining conlifcts are whitespace, the version of each conflict from this Pull Request can be selected to resolve the conflict.

**Pull request closed without merging**
